import getAllpost from '@/lib/getAllpost'
import Link from 'next/link'
import React from 'react'
import { Agdasima } from 'next/font/google'
const agdasima =Agdasima({subsets:['latin'], weight:['400','700']})
export const metadata = {
  title: "Blog-page",
  description: "Generated by create next app",
};
const page =async () => {
  const allpost = await getAllpost()
  console.log(allpost);
  
  return (
    <>
   <div className='text-[39px] font-blod'>
    <h1 className='text-center'>Blog page</h1>
   </div>
   {
    allpost.map((item)=>(
      <Link href={`/blog/${item.id}`}>
      <div className='w-[800px] mx-auto mt-4'>
      <h2 className={`${agdasima.className} font-bold text-[25px]`}>Title:{item.title}</h2>
     </div>
      </Link>
      
    ))
   }
  
    <Link href={'/blog/blogauthor'}>
    <button className='py-2 px-4 bg-[black] text-white mt-4'>Click here</button>
    </Link>

    </>
    
  )
}

export default page
