import Image from 'next/image'
import React from 'react'
import aboutimg from '../../public/pexels-chloekalaartist-1043474.jpg'
export const metadata = {
  title: "About-page",
  description: "Generated by create next app",
};
const page = () => {
  return (
  <>
  <div className='w-[1140px]  h-[400px] flex mx-auto mt-4'>
  <div className='flex gap-2'>
    <div className='w-[30%]'>
      <Image src={aboutimg} alt='aboutimg' className='w-full h-[400px]'/>
    </div>
    <div className='w-[70%] flex justify-center items-center'>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae veritatis pariatur deleniti enim recusandae, tempore nulla sint cupiditate laboriosam odio voluptate accusantium reprehenderit nemo temporibus expedita tenetur, deserunt quae! Expedita sint commodi ipsa, quia deserunt magni laborum fuga quis accusantium, totam odit provident tempora animi voluptas officiis earum mollitia quod? Neque fugit hic corporis asperiores velit magni adipisci, esse facere quae obcaecati cum, est qui praesentium eum natus fugiat aperiam repellendus ipsum, iusto aut reiciendis! Beatae deserunt, debitis consequatur sint, in facere facilis vitae voluptas impedit ad et, sapiente ratione nemo minus harum maiores quod atque eos velit iste fugit.</p>
    </div>
  </div>
  </div>
  
  </>
  )
}

export default page
