import "./globals.css";
import { Navbar } from "./Componnents/Navbar";
import {Josefin_Sans} from "next/font/google"
const jesoefin = Josefin_Sans({subsets:["latin"]})
export const metadata = {
  title:{
    default:"Hello-world",
    template:"%s। Hello-world"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jesoefin.className} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
